---
- hosts: ec2
  become: true
  tasks:
    - name: Deshabilitar docker
      service:
        name: docker
        enabled: false
        state: stopped

    - name: Instalar Apache httpd
      yum:
        name: httpd
        state: latest

    - name: Iniciar Apache httpd
      service:
        name: httpd
        enabled: true
        state: started

    - name: Install app
      copy:
        src: ../hello-2048/public_html/
        dest: /var/www/html/
        owner: apache
        group: apache
        mode: "0644"
        directory_mode: "0755"
