---
- hosts: all
  become: true
  vars:
    ansible_user: ec2-user
  tasks:
    - name: Install app
      copy:
        src: ./public_html/
        dest: /var/www/html/
        owner: apache
        group: apache
        mode: "0644"
        directory_mode: "0755"
